module.exports =  {
    categories: [
        {category: 'Category 1', id: 'category_1'}, 
        {category: 'Category 2', id: 'category_2'}, 
        {category: 'Category 3', id: 'category_3'}, 
        {category: 'Category 4', id: 'category_4'}, 
        {category: 'Category 5', id: 'category_5'}, 
        {category: 'Category 6', id: 'category_6'},
    ],

    subjects: [
        {subject: 'Category 1 Subject 1', id: 'category_1_subject_1', category_id: 'category_1'},
        {subject: 'Category 1 Subject 2', id: 'category_1_subject_2', category_id: 'category_1'},
        {subject: 'Category 1 Subject 3', id: 'category_1_subject_3', category_id: 'category_1'},
        {subject: 'Category 1 Subject 4', id: 'category_1_subject_4', category_id: 'category_1'},
        {subject: 'Category 1 Subject 5', id: 'category_1_subject_5', category_id: 'category_1'},
        
        {subject: 'Category 2 Subject 1', id: 'category_2_subject_1', category_id: 'category_2'},
        {subject: 'Category 2 Subject 2', id: 'category_2_subject_2', category_id: 'category_2'},
        {subject: 'Category 2 Subject 3', id: 'category_2_subject_3', category_id: 'category_2'},
        {subject: 'Category 2 Subject 4', id: 'category_2_subject_4', category_id: 'category_2'},
        {subject: 'Category 2 Subject 5', id: 'category_2_subject_5', category_id: 'category_2'},
        
        {subject: 'Category 3 Subject 1', id: 'category_3_subject_1', category_id: 'category_3'},
        {subject: 'Category 3 Subject 2', id: 'category_3_subject_2', category_id: 'category_3'},
        {subject: 'Category 3 Subject 3', id: 'category_3_subject_3', category_id: 'category_3'},
        {subject: 'Category 3 Subject 4', id: 'category_3_subject_4', category_id: 'category_3'},
        {subject: 'Category 3 Subject 5', id: 'category_3_subject_5', category_id: 'category_3'},
    
        {subject: 'Category 4 Subject 1', id: 'category_4_subject_1', category_id: 'category_4'},
        {subject: 'Category 4 Subject 2', id: 'category_4_subject_2', category_id: 'category_4'},
        {subject: 'Category 4 Subject 3', id: 'category_4_subject_3', category_id: 'category_4'},
        {subject: 'Category 4 Subject 4', id: 'category_4_subject_4', category_id: 'category_4'},
        {subject: 'Category 4 Subject 5', id: 'category_4_subject_5', category_id: 'category_4'},
        
        {subject: 'Category 5 Subject 1', id: 'category_5_subject_1', category_id: 'category_5'},
        {subject: 'Category 5 Subject 2', id: 'category_5_subject_2', category_id: 'category_5'},
        {subject: 'Category 5 Subject 3', id: 'category_5_subject_3', category_id: 'category_5'},
        {subject: 'Category 5 Subject 4', id: 'category_5_subject_4', category_id: 'category_5'},
        {subject: 'Category 5 Subject 5', id: 'category_5_subject_5', category_id: 'category_5'},
    
        {subject: 'Category 6 Subject 1', id: 'category_6_subject_1', category_id: 'category_6'},
        {subject: 'Category 6 Subject 2', id: 'category_6_subject_2', category_id: 'category_6'},
        {subject: 'Category 6 Subject 3', id: 'category_6_subject_3', category_id: 'category_6'},
        {subject: 'Category 6 Subject 4', id: 'category_6_subject_4', category_id: 'category_6'},
        {subject: 'Category 6 Subject 5', id: 'category_6_subject_5', category_id: 'category_6'},
    ],

    tags: [
        {tag: 'Category 1 Subject 1 Tag 1', id: 'c_1_s_1_t_1', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 2', id: 'c_1_s_1_t_2', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 3', id: 'c_1_s_1_t_3', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 4', id: 'c_1_s_1_t_4', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 5', id: 'c_1_s_1_t_5', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 6', id: 'c_1_s_1_t_6', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 7', id: 'c_1_s_1_t_7', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 8', id: 'c_1_s_1_t_8', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 9', id: 'c_1_s_1_t_9', subject_id: 'category_1_subject_1'},
        {tag: 'Category 1 Subject 1 Tag 10', id: 'c_1_s_1_t_10', subject_id: 'category_1_subject_1'},
    
        {tag: 'Category 1 Subject 2 Tag 1', id: 'c_1_s_2_t_1', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 2', id: 'c_1_s_2_t_2', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 3', id: 'c_1_s_2_t_3', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 4', id: 'c_1_s_2_t_4', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 5', id: 'c_1_s_2_t_5', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 6', id: 'c_1_s_2_t_6', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 7', id: 'c_1_s_2_t_7', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 8', id: 'c_1_s_2_t_8', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 9', id: 'c_1_s_2_t_9', subject_id: 'category_1_subject_2'},
        {tag: 'Category 1 Subject 2 Tag 10', id: 'c_1_s_2_t_10', subject_id: 'category_1_subject_2'},
        
        {tag: 'Category 1 Subject 3 Tag 1', id: 'c_1_s_3_t_1', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 2', id: 'c_1_s_3_t_2', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 3', id: 'c_1_s_3_t_3', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 4', id: 'c_1_s_3_t_4', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 5', id: 'c_1_s_3_t_5', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 6', id: 'c_1_s_3_t_6', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 7', id: 'c_1_s_3_t_7', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 8', id: 'c_1_s_3_t_8', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 9', id: 'c_1_s_3_t_9', subject_id: 'category_1_subject_3'},
        {tag: 'Category 1 Subject 3 Tag 10', id: 'c_1_s_3_t_10', subject_id: 'category_1_subject_3'},
        
        {tag: 'Category 1 Subject 4 Tag 1', id: 'c_1_s_4_t_1', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 2', id: 'c_1_s_4_t_2', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 3', id: 'c_1_s_4_t_3', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 4', id: 'c_1_s_4_t_4', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 5', id: 'c_1_s_4_t_5', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 6', id: 'c_1_s_4_t_6', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 7', id: 'c_1_s_4_t_7', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 8', id: 'c_1_s_4_t_8', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 9', id: 'c_1_s_4_t_9', subject_id: 'category_1_subject_4'},
        {tag: 'Category 1 Subject 4 Tag 10', id: 'c_1_s_4_t_10', subject_id: 'category_1_subject_4'},
        
        {tag: 'Category 1 Subject 5 Tag 1', id: 'c_1_s_5_t_1', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 2', id: 'c_1_s_5_t_2', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 3', id: 'c_1_s_5_t_3', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 4', id: 'c_1_s_5_t_4', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 5', id: 'c_1_s_5_t_5', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 6', id: 'c_1_s_5_t_6', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 7', id: 'c_1_s_5_t_7', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 8', id: 'c_1_s_5_t_8', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 9', id: 'c_1_s_5_t_9', subject_id: 'category_1_subject_5'},
        {tag: 'Category 1 Subject 5 Tag 10', id: 'c_1_s_5_t_10', subject_id: 'category_1_subject_5'},


        {tag: 'Category 2 Subject 1 Tag 1', id: 'c_2_s_1_t_1', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 2', id: 'c_2_s_1_t_2', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 3', id: 'c_2_s_1_t_3', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 4', id: 'c_2_s_1_t_4', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 5', id: 'c_2_s_1_t_5', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 6', id: 'c_2_s_1_t_6', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 7', id: 'c_2_s_1_t_7', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 8', id: 'c_2_s_1_t_8', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 9', id: 'c_2_s_1_t_9', subject_id: 'category_2_subject_1'},
        {tag: 'Category 2 Subject 1 Tag 10', id: 'c_2_s_1_t_10', subject_id: 'category_2_subject_1'},
        
        {tag: 'Category 2 Subject 2 Tag 1', id: 'c_2_s_2_t_1', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 2', id: 'c_2_s_2_t_2', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 3', id: 'c_2_s_2_t_3', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 4', id: 'c_2_s_2_t_4', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 5', id: 'c_2_s_2_t_5', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 6', id: 'c_2_s_2_t_6', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 7', id: 'c_2_s_2_t_7', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 8', id: 'c_2_s_2_t_8', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 9', id: 'c_2_s_2_t_9', subject_id: 'category_2_subject_2'},
        {tag: 'Category 2 Subject 2 Tag 10', id: 'c_2_s_2_t_10', subject_id: 'category_2_subject_2'},        

        {tag: 'Category 2 Subject 3 Tag 1', id: 'c_2_s_3_t_1', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 2', id: 'c_2_s_3_t_2', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 3', id: 'c_2_s_3_t_3', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 4', id: 'c_2_s_3_t_4', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 5', id: 'c_2_s_3_t_5', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 6', id: 'c_2_s_3_t_6', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 7', id: 'c_2_s_3_t_7', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 8', id: 'c_2_s_3_t_8', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 9', id: 'c_2_s_3_t_9', subject_id: 'category_2_subject_3'},
        {tag: 'Category 2 Subject 3 Tag 10', id: 'c_2_s_3_t_10', subject_id: 'category_2_subject_3'},        

        {tag: 'Category 2 Subject 4 Tag 1', id: 'c_2_s_4_t_1', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 2', id: 'c_2_s_4_t_2', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 3', id: 'c_2_s_4_t_3', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 4', id: 'c_2_s_4_t_4', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 5', id: 'c_2_s_4_t_5', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 6', id: 'c_2_s_4_t_6', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 7', id: 'c_2_s_4_t_7', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 8', id: 'c_2_s_4_t_8', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 9', id: 'c_2_s_4_t_9', subject_id: 'category_2_subject_4'},
        {tag: 'Category 2 Subject 4 Tag 10', id: 'c_2_s_4_t_10', subject_id: 'category_2_subject_4'},        

        {tag: 'Category 2 Subject 5 Tag 1', id: 'c_2_s_5_t_1', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 2', id: 'c_2_s_5_t_2', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 3', id: 'c_2_s_5_t_3', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 4', id: 'c_2_s_5_t_4', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 5', id: 'c_2_s_5_t_5', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 6', id: 'c_2_s_5_t_6', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 7', id: 'c_2_s_5_t_7', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 8', id: 'c_2_s_5_t_8', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 9', id: 'c_2_s_5_t_9', subject_id: 'category_2_subject_5'},
        {tag: 'Category 2 Subject 5 Tag 10', id: 'c_2_s_5_t_10', subject_id: 'category_2_subject_5'},

        
        {tag: 'Category 3 Subject 1 Tag 1', id: 'c_3_s_1_t_1', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 2', id: 'c_3_s_1_t_2', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 3', id: 'c_3_s_1_t_3', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 4', id: 'c_3_s_1_t_4', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 5', id: 'c_3_s_1_t_5', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 6', id: 'c_3_s_1_t_6', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 7', id: 'c_3_s_1_t_7', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 8', id: 'c_3_s_1_t_8', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 9', id: 'c_3_s_1_t_9', subject_id: 'category_3_subject_1'},
        {tag: 'Category 3 Subject 1 Tag 10', id: 'c_3_s_1_t_10', subject_id: 'category_3_subject_1'},

        {tag:  'Category 3 Subject 2  Tag 1', id: 'c_3_s_2_t_1', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 2', id: 'c_3_s_2_t_2', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 3', id: 'c_3_s_2_t_3', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 4', id: 'c_3_s_2_t_4', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 5', id: 'c_3_s_2_t_5', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 6', id: 'c_3_s_2_t_6', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 7', id: 'c_3_s_2_t_7', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 8', id: 'c_3_s_2_t_8', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 9', id: 'c_3_s_2_t_9', subject_id: 'category_3_subject_2'},
        {tag:  'Category 3 Subject 2  Tag 10', id:'c_3_s_2_t_10',subject_id: 'category_3_subject_2'},        

        {tag:  'Category 3 Subject 3  Tag 1', id: 'c_3_s_3_t_1', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 2', id: 'c_3_s_3_t_2', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 3', id: 'c_3_s_3_t_3', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 4', id: 'c_3_s_3_t_4', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 5', id: 'c_3_s_3_t_5', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 6', id: 'c_3_s_3_t_6', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 7', id: 'c_3_s_3_t_7', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 8', id: 'c_3_s_3_t_8', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 9', id: 'c_3_s_3_t_9', subject_id: 'category_3_subject_3'},
        {tag:  'Category 3 Subject 3  Tag 10', id:'c_3_s_3_t_10',subject_id: 'category_3_subject_3'},        

        {tag:  'Category 3 Subject 4  Tag 1', id: 'c_3_s_4_t_1', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 2', id: 'c_3_s_4_t_2', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 3', id: 'c_3_s_4_t_3', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 4', id: 'c_3_s_4_t_4', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 5', id: 'c_3_s_4_t_5', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 6', id: 'c_3_s_4_t_6', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 7', id: 'c_3_s_4_t_7', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 8', id: 'c_3_s_4_t_8', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 9', id: 'c_3_s_4_t_9', subject_id: 'category_3_subject_4'},
        {tag:  'Category 3 Subject 4  Tag 10', id:'c_3_s_4_t_10',subject_id: 'category_3_subject_4'},  
        
        {tag:  'Category 3 Subject 5  Tag 1', id: 'c_3_s_5_t_1', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 2', id: 'c_3_s_5_t_2', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 3', id: 'c_3_s_5_t_3', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 4', id: 'c_3_s_5_t_4', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 5', id: 'c_3_s_5_t_5', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 6', id: 'c_3_s_5_t_6', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 7', id: 'c_3_s_5_t_7', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 8', id: 'c_3_s_5_t_8', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 9', id: 'c_3_s_5_t_9', subject_id: 'category_3_subject_5'},
        {tag:  'Category 3 Subject 5  Tag 10', id:'c_3_s_5_t_10',subject_id: 'category_3_subject_5'},  

        
        {tag:  'Category 4 Subject 1  Tag 1', id: 'c_4_s_1_t_1', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 2', id: 'c_4_s_1_t_2', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 3', id: 'c_4_s_1_t_3', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 4', id: 'c_4_s_1_t_4', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 5', id: 'c_4_s_1_t_5', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 6', id: 'c_4_s_1_t_6', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 7', id: 'c_4_s_1_t_7', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 8', id: 'c_4_s_1_t_8', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 9', id: 'c_4_s_1_t_9', subject_id: 'category_4_subject_1'},
        {tag:  'Category 4 Subject 1  Tag 10', id:'c_4_s_1_t_10',subject_id: 'category_4_subject_1'},  
        
        {tag:  'Category 4 Subject 2  Tag 1', id: 'c_4_s_2_t_1', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 2', id: 'c_4_s_2_t_2', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 3', id: 'c_4_s_2_t_3', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 4', id: 'c_4_s_2_t_4', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 5', id: 'c_4_s_2_t_5', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 6', id: 'c_4_s_2_t_6', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 7', id: 'c_4_s_2_t_7', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 8', id: 'c_4_s_2_t_8', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 9', id: 'c_4_s_2_t_9', subject_id: 'category_4_subject_2'},
        {tag:  'Category 4 Subject 2  Tag 10', id:'c_4_s_2_t_10',subject_id: 'category_4_subject_2'},  
        
        {tag:  'Category 4 Subject 3  Tag 1', id: 'c_4_s_3_t_1', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 2', id: 'c_4_s_3_t_2', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 3', id: 'c_4_s_3_t_3', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 4', id: 'c_4_s_3_t_4', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 5', id: 'c_4_s_3_t_5', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 6', id: 'c_4_s_3_t_6', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 7', id: 'c_4_s_3_t_7', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 8', id: 'c_4_s_3_t_8', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 9', id: 'c_4_s_3_t_9', subject_id: 'category_4_subject_3'},
        {tag:  'Category 4 Subject 3  Tag 10', id:'c_4_s_3_t_10',subject_id: 'category_4_subject_3'},  
        
        {tag:  'Category 4 Subject 4  Tag 1', id: 'c_4_s_4_t_1', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 2', id: 'c_4_s_4_t_2', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 3', id: 'c_4_s_4_t_3', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 4', id: 'c_4_s_4_t_4', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 5', id: 'c_4_s_4_t_5', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 6', id: 'c_4_s_4_t_6', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 7', id: 'c_4_s_4_t_7', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 8', id: 'c_4_s_4_t_8', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 9', id: 'c_4_s_4_t_9', subject_id: 'category_4_subject_4'},
        {tag:  'Category 4 Subject 4  Tag 10', id:'c_4_s_4_t_10',subject_id: 'category_4_subject_4'},  
        
        {tag:  'Category 4 Subject 5  Tag 1', id: 'c_4_s_5_t_1', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 2', id: 'c_4_s_5_t_2', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 3', id: 'c_4_s_5_t_3', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 4', id: 'c_4_s_5_t_4', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 5', id: 'c_4_s_5_t_5', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 6', id: 'c_4_s_5_t_6', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 7', id: 'c_4_s_5_t_7', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 8', id: 'c_4_s_5_t_8', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 9', id: 'c_4_s_5_t_9', subject_id: 'category_4_subject_5'},
        {tag:  'Category 4 Subject 5  Tag 10', id:'c_4_s_5_t_10',subject_id: 'category_4_subject_5'},  
        
        
        {tag:  'Category 5 Subject 1  Tag 1', id: 'c_5_s_1_t_1', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 2', id: 'c_5_s_1_t_2', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 3', id: 'c_5_s_1_t_3', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 4', id: 'c_5_s_1_t_4', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 5', id: 'c_5_s_1_t_5', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 6', id: 'c_5_s_1_t_6', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 7', id: 'c_5_s_1_t_7', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 8', id: 'c_5_s_1_t_8', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 9', id: 'c_5_s_1_t_9', subject_id: 'category_5_subject_1'},
        {tag:  'Category 5 Subject 1  Tag 10', id:'c_5_s_1_t_10',subject_id: 'category_5_subject_1'},  
        
        {tag:  'Category 5 Subject 2  Tag 1', id: 'c_5_s_2_t_1', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 2', id: 'c_5_s_2_t_2', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 3', id: 'c_5_s_2_t_3', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 4', id: 'c_5_s_2_t_4', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 5', id: 'c_5_s_2_t_5', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 6', id: 'c_5_s_2_t_6', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 7', id: 'c_5_s_2_t_7', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 8', id: 'c_5_s_2_t_8', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 9', id: 'c_5_s_2_t_9', subject_id: 'category_5_subject_2'},
        {tag:  'Category 5 Subject 2  Tag 10', id:'c_5_s_2_t_10',subject_id: 'category_5_subject_2'},  
        
        {tag:  'Category 5 Subject 3  Tag 1', id: 'c_5_s_3_t_1', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 2', id: 'c_5_s_3_t_2', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 3', id: 'c_5_s_3_t_3', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 4', id: 'c_5_s_3_t_4', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 5', id: 'c_5_s_3_t_5', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 6', id: 'c_5_s_3_t_6', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 7', id: 'c_5_s_3_t_7', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 8', id: 'c_5_s_3_t_8', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 9', id: 'c_5_s_3_t_9', subject_id: 'category_5_subject_3'},
        {tag:  'Category 5 Subject 3  Tag 10', id:'c_5_s_3_t_10',subject_id: 'category_5_subject_3'},  
        
        {tag:  'Category 5 Subject 4  Tag 1', id: 'c_5_s_4_t_1', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 2', id: 'c_5_s_4_t_2', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 3', id: 'c_5_s_4_t_3', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 4', id: 'c_5_s_4_t_4', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 5', id: 'c_5_s_4_t_5', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 6', id: 'c_5_s_4_t_6', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 7', id: 'c_5_s_4_t_7', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 8', id: 'c_5_s_4_t_8', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 9', id: 'c_5_s_4_t_9', subject_id: 'category_5_subject_4'},
        {tag:  'Category 5 Subject 4  Tag 10', id:'c_5_s_4_t_10',subject_id: 'category_5_subject_4'},  
        
        {tag:  'Category 5 Subject 5  Tag 1', id: 'c_5_s_5_t_1', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 2', id: 'c_5_s_5_t_2', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 3', id: 'c_5_s_5_t_3', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 4', id: 'c_5_s_5_t_4', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 5', id: 'c_5_s_5_t_5', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 6', id: 'c_5_s_5_t_6', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 7', id: 'c_5_s_5_t_7', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 8', id: 'c_5_s_5_t_8', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 9', id: 'c_5_s_5_t_9', subject_id: 'category_5_subject_5'},
        {tag:  'Category 5 Subject 5  Tag 10', id:'c_5_s_5_t_10',subject_id: 'category_5_subject_5'},  
        
        
        {tag:  'Category 6 Subject 1  Tag 1', id: 'c_6_s_1_t_1', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 2', id: 'c_6_s_1_t_2', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 3', id: 'c_6_s_1_t_3', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 4', id: 'c_6_s_1_t_4', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 5', id: 'c_6_s_1_t_5', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 6', id: 'c_6_s_1_t_6', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 7', id: 'c_6_s_1_t_7', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 8', id: 'c_6_s_1_t_8', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 9', id: 'c_6_s_1_t_9', subject_id: 'category_6_subject_1'},
        {tag:  'Category 6 Subject 1  Tag 10', id:'c_6_s_1_t_10',subject_id: 'category_6_subject_1'},  
        
        {tag:  'Category 6 Subject 2  Tag 1', id: 'c_6_s_2_t_1', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 2', id: 'c_6_s_2_t_2', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 3', id: 'c_6_s_2_t_3', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 4', id: 'c_6_s_2_t_4', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 5', id: 'c_6_s_2_t_5', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 6', id: 'c_6_s_2_t_6', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 7', id: 'c_6_s_2_t_7', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 8', id: 'c_6_s_2_t_8', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 9', id: 'c_6_s_2_t_9', subject_id: 'category_6_subject_2'},
        {tag:  'Category 6 Subject 2  Tag 10', id:'c_6_s_2_t_10',subject_id: 'category_6_subject_2'},  
        
        {tag:  'Category 6 Subject 3  Tag 1', id: 'c_6_s_3_t_1', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 2', id: 'c_6_s_3_t_2', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 3', id: 'c_6_s_3_t_3', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 4', id: 'c_6_s_3_t_4', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 5', id: 'c_6_s_3_t_5', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 6', id: 'c_6_s_3_t_6', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 7', id: 'c_6_s_3_t_7', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 8', id: 'c_6_s_3_t_8', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 9', id: 'c_6_s_3_t_9', subject_id: 'category_6_subject_3'},
        {tag:  'Category 6 Subject 3  Tag 10', id:'c_6_s_3_t_10',subject_id: 'category_6_subject_3'},  
        
        {tag:  'Category 6 Subject 4  Tag 1', id: 'c_6_s_4_t_1', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 2', id: 'c_6_s_4_t_2', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 3', id: 'c_6_s_4_t_3', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 4', id: 'c_6_s_4_t_4', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 5', id: 'c_6_s_4_t_5', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 6', id: 'c_6_s_4_t_6', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 7', id: 'c_6_s_4_t_7', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 8', id: 'c_6_s_4_t_8', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 9', id: 'c_6_s_4_t_9', subject_id: 'category_6_subject_4'},
        {tag:  'Category 6 Subject 4  Tag 10', id:'c_6_s_4_t_10',subject_id: 'category_6_subject_4'},  
        
        {tag:  'Category 6 Subject 5  Tag 1', id: 'c_6_s_5_t_1', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 2', id: 'c_6_s_5_t_2', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 3', id: 'c_6_s_5_t_3', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 4', id: 'c_6_s_5_t_4', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 5', id: 'c_6_s_5_t_5', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 6', id: 'c_6_s_5_t_6', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 7', id: 'c_6_s_5_t_7', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 8', id: 'c_6_s_5_t_8', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 9', id: 'c_6_s_5_t_9', subject_id: 'category_6_subject_5'},
        {tag:  'Category 6 Subject 5  Tag 10', id:'c_6_s_5_t_10',subject_id: 'category_6_subject_5'},  

    ]
}